/* Copyright Applied Industrial Logic Limited 2002. All rights Reserved */
/*
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later 
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51 
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

package com.ail.financial;

import com.ail.annotation.TypeDefinition;
import com.ail.core.Identified;
import com.ail.core.Type;

@TypeDefinition
public abstract class PaymentMethod extends Type implements Identified {
    String identifier;
    private static final long serialVersionUID = 1L;

    public void setId(String id) {
        throw new IllegalStateException("A PaymentMethod's ID can only be generated by the PaymentMethod class, it cannot be set externally");
    }
    
    @Override
    public boolean compareById(Object that) {
        return (that instanceof PaymentMethod && ((PaymentMethod) that).getId().equals(identifier));
    }
}
