// Generated by com.ail.annotation.Processor

package com.ail.core.product;


import com.ail.core.command.Accessor;
import com.ail.core.command.Argument;
import com.ail.core.command.CommandImpl;

public class GetNamespacesHistoryCommandImpl extends CommandImpl implements com.ail.core.product.ClearProductCacheService.GetNamespacesHistoryCommand {
  static final long serialVersionUID = 4559144639366321152L;

  private Accessor accessor;
  private com.ail.core.product.ClearProductCacheService.GetNamespacesHistoryArgument args;

  public GetNamespacesHistoryCommandImpl() {
    super();
    args=new com.ail.core.product.GetNamespacesHistoryArgumentImpl();
  }

  public GetNamespacesHistoryCommandImpl(Accessor accessor, com.ail.core.product.ClearProductCacheService.GetNamespacesHistoryArgument args) {
    setAccessor(accessor);
    setArgs(args);
  }

  public Accessor getAccessor() {
    return accessor;
  }

  public void setAccessor(Accessor accessor) {
    this.accessor=accessor;
  }

  public void setService(Accessor accessor) {
    this.accessor=accessor;
  }

  public void setArgs(Argument arg) {
    this.args=(com.ail.core.product.ClearProductCacheService.GetNamespacesHistoryArgument)arg;
  }

  public Argument getArgs() {
    return args;
  }

  public java.lang.String getNamespaceArg() {
    return args.getNamespaceArg();
  }

  public java.util.Collection<java.lang.String> getNamespacesRet() {
    return args.getNamespacesRet();
  }

  public void setNamespaceArg(java.lang.String namespaceArg) {
    args.setProductNameArg(namespaceArg);
  }

  public void setNamespacesRet(java.util.Collection<java.lang.String> namespacesRet) {
    args.setNamespacesRet(namespacesRet);
  }

}