// Generated by com.ail.annotation.Processor

package com.ail.core.product;

import com.ail.core.command.ArgumentImpl;

public class GetNamespacesHistoryArgumentImpl extends ArgumentImpl implements com.ail.core.product.ClearProductCacheService.GetNamespacesHistoryArgument {
  static final long serialVersionUID = 2403337873779771392L;

  private java.lang.String namespaceArg;
  private java.util.Collection<java.lang.String> namespacesRet;

  public java.lang.String getNamespaceArg() {
    return namespaceArg;
  }

  public java.util.Collection<java.lang.String> getNamespacesRet() {
    return namespacesRet;
  }

  public void setNamespaceArg(java.lang.String namespaceArg) {
    this.namespaceArg=namespaceArg;
  }

  public void setNamespacesRet(java.util.Collection<java.lang.String> namespacesRet) {
    this.namespacesRet=namespacesRet;
  }

}
