insert into couENCountry (name, country, validFrom, validTo) values('AF', 'AFGHANISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AX', 'ALAND ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AL', 'ALBANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DZ', 'ALGERIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AS', 'AMERICAN SAMOA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AD', 'ANDORRA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AO', 'ANGOLA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AI', 'ANGUILLA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AQ', 'ANTARCTICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AG', 'ANTIGUA AND BARBUDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AR', 'ARGENTINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AM', 'ARMENIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AW', 'ARUBA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AU', 'AUSTRALIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AT', 'AUSTRIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AZ', 'AZERBAIJAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BS', 'BAHAMAS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BH', 'BAHRAIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BD', 'BANGLADESH', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BB', 'BARBADOS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BY', 'BELARUS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BE', 'BELGIUM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BZ', 'BELIZE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BJ', 'BENIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BM', 'BERMUDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BT', 'BHUTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BO', 'BOLIVIA, PLURINATIONAL STATE OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BA', 'BOSNIA AND HERZEGOVINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BW', 'BOTSWANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BV', 'BOUVET ISLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BR', 'BRAZIL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IO', 'BRITISH INDIAN OCEAN TERRITORY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BN', 'BRUNEI DARUSSALAM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BG', 'BULGARIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BF', 'BURKINA FASO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BI', 'BURUNDI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KH', 'CAMBODIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CM', 'CAMEROON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CA', 'CANADA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CV', 'CAPE VERDE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KY', 'CAYMAN ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CF', 'CENTRAL AFRICAN REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TD', 'CHAD', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CL', 'CHILE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CN', 'CHINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CX', 'CHRISTMAS ISLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CC', 'COCOS (KEELING) ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CO', 'COLOMBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KM', 'COMOROS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CG', 'CONGO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CK', 'COOK ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CR', 'COSTA RICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CI', 'COTE DIVOIRE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HR', 'CROATIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CU', 'CUBA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CW', 'CURACAO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CY', 'CYPRUS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CZ', 'CZECH REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DK', 'DENMARK', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DJ', 'DJIBOUTI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DM', 'DOMINICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DO', 'DOMINICAN REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EC', 'ECUADOR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EG', 'EGYPT', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SV', 'EL SALVADOR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GQ', 'EQUATORIAL GUINEA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ER', 'ERITREA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EE', 'ESTONIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ET', 'ETHIOPIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FK', 'FALKLAND ISLANDS (MALVINAS)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FO', 'FAROE ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FJ', 'FIJI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FI', 'FINLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FR', 'FRANCE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GF', 'FRENCH GUIANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PF', 'FRENCH POLYNESIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TF', 'FRENCH SOUTHERN TERRITORIES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GA', 'GABON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GM', 'GAMBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GE', 'GEORGIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DE', 'GERMANY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GH', 'GHANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GI', 'GIBRALTAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GR', 'GREECE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GL', 'GREENLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GD', 'GRENADA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GP', 'GUADELOUPE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GU', 'GUAM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GT', 'GUATEMALA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GG', 'GUERNSEY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GN', 'GUINEA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GW', 'GUINEA-BISSAU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GY', 'GUYANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HT', 'HAITI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VA', 'HOLY SEE (VATICAN CITY STATE)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HN', 'HONDURAS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HK', 'HONG KONG', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HU', 'HUNGARY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IS', 'ICELAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IN', 'INDIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ID', 'INDONESIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IR', 'IRAN, ISLAMIC REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IQ', 'IRAQ', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IE', 'IRELAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IM', 'ISLE OF MAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IL', 'ISRAEL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IT', 'ITALY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JM', 'JAMAICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JP', 'JAPAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JE', 'JERSEY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JO', 'JORDAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KZ', 'KAZAKHSTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KE', 'KENYA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KI', 'KIRIBATI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KP', 'KOREA, DEMOCRATIC PEOPLES REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KR', 'KOREA, REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KW', 'KUWAIT', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KG', 'KYRGYZSTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LA', 'LAO PEOPLES DEMOCRATIC REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LV', 'LATVIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LB', 'LEBANON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LS', 'LESOTHO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LR', 'LIBERIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LY', 'LIBYA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LI', 'LIECHTENSTEIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LT', 'LITHUANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LU', 'LUXEMBOURG', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MO', 'MACAO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MG', 'MADAGASCAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MW', 'MALAWI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MY', 'MALAYSIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MV', 'MALDIVES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ML', 'MALI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MT', 'MALTA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MH', 'MARSHALL ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MQ', 'MARTINIQUE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MR', 'MAURITANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MU', 'MAURITIUS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('YT', 'MAYOTTE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MX', 'MEXICO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FM', 'MICRONESIA, FEDERATED STATES OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MD', 'MOLDOVA, REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MC', 'MONACO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MN', 'MONGOLIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ME', 'MONTENEGRO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MS', 'MONTSERRAT', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MA', 'MOROCCO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MZ', 'MOZAMBIQUE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MM', 'MYANMAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NA', 'NAMIBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NR', 'NAURU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NP', 'NEPAL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NL', 'NETHERLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NC', 'NEW CALEDONIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NZ', 'NEW ZEALAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NI', 'NICARAGUA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NE', 'NIGER', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NG', 'NIGERIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NU', 'NIUE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NF', 'NORFOLK ISLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MP', 'NORTHERN MARIANA ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NO', 'NORWAY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('OM', 'OMAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PK', 'PAKISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PW', 'PALAU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PS', 'PALESTINE, STATE OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PA', 'PANAMA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PG', 'PAPUA NEW GUINEA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PY', 'PARAGUAY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PE', 'PERU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PH', 'PHILIPPINES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PN', 'PITCAIRN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PL', 'POLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PT', 'PORTUGAL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PR', 'PUERTO RICO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('QA', 'QATAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RE', 'REUNION', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RO', 'ROMANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RU', 'RUSSIAN FEDERATION', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RW', 'RWANDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BL', 'SAINT BARTHELEMY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KN', 'SAINT KITTS AND NEVIS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LC', 'SAINT LUCIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MF', 'SAINT MARTIN (FRENCH PART)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PM', 'SAINT PIERRE AND MIQUELON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VC', 'SAINT VINCENT AND THE GRENADINES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('WS', 'SAMOA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SM', 'SAN MARINO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ST', 'SAO TOME AND PRINCIPE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SA', 'SAUDI ARABIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SN', 'SENEGAL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RS', 'SERBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SC', 'SEYCHELLES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SL', 'SIERRA LEONE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SG', 'SINGAPORE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SX', 'SINT MAARTEN (DUTCH PART)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SK', 'SLOVAKIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SI', 'SLOVENIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SB', 'SOLOMON ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SO', 'SOMALIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ZA', 'SOUTH AFRICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SS', 'SOUTH SUDAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ES', 'SPAIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LK', 'SRI LANKA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SD', 'SUDAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SR', 'SURINAME', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SJ', 'SVALBARD AND JAN MAYEN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SZ', 'SWAZILAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SE', 'SWEDEN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CH', 'SWITZERLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SY', 'SYRIAN ARAB REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TW', 'TAIWAN, PROVINCE OF CHINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TJ', 'TAJIKISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TZ', 'TANZANIA, UNITED REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TH', 'THAILAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TL', 'TIMOR-LESTE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TG', 'TOGO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TK', 'TOKELAU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TO', 'TONGA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TT', 'TRINIDAD AND TOBAGO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TN', 'TUNISIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TR', 'TURKEY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TM', 'TURKMENISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TC', 'TURKS AND CAICOS ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TV', 'TUVALU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UG', 'UGANDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UA', 'UKRAINE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AE', 'UNITED ARAB EMIRATES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GB', 'UNITED KINGDOM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('US', 'UNITED STATES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UY', 'URUGUAY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UZ', 'UZBEKISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VU', 'VANUATU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VN', 'VIET NAM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VG', 'VIRGIN ISLANDS, BRITISH', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VI', 'VIRGIN ISLANDS, U.S.', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('WF', 'WALLIS AND FUTUNA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EH', 'WESTERN SAHARA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('YE', 'YEMEN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ZM', 'ZAMBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ZW', 'ZIMBABWE', null, null);
