insert into natENNationality (name, validFrom, validTo) values('AFGHAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ALBANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ALGERIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AMERICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ANDORRAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ANGOLAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ANTIGUANS', null, null);
insert into natENNationality (name, validFrom, validTo) values('ARGENTINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ARMENIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AUSTRALIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AUSTRIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AZERBAIJANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('BAHAMIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BAHRAINI', null, null);
insert into natENNationality (name, validFrom, validTo) values('BANGLADESHI', null, null);
insert into natENNationality (name, validFrom, validTo) values('BARBADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BARBUDANS', null, null);
insert into natENNationality (name, validFrom, validTo) values('BATSWANA', null, null);
insert into natENNationality (name, validFrom, validTo) values('BELARUSIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BELGIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BELIZEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BENINESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BHUTANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BOLIVIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BOSNIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BRAZILIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BRITISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('BRUNEIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BULGARIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BURKINABE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BURMESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BURUNDIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CAMBODIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CAMEROONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CANADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CAPE VERDEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CENTRAL AFRICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CHADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CHILEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CHINESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('COLOMBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('COMORAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CONGOLESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('COSTA RICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CROATIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CUBAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CYPRIOT', null, null);
insert into natENNationality (name, validFrom, validTo) values('CZECH', null, null);
insert into natENNationality (name, validFrom, validTo) values('DANISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('DJIBOUTI', null, null);
insert into natENNationality (name, validFrom, validTo) values('DOMINICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('DUTCH', null, null);
insert into natENNationality (name, validFrom, validTo) values('EAST TIMORESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('ECUADOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('EGYPTIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('EMIRIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('EQUATORIAL GUINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ERITREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ESTONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ETHIOPIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('FIJIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('FILIPINO', null, null);
insert into natENNationality (name, validFrom, validTo) values('FINNISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('FRENCH', null, null);
insert into natENNationality (name, validFrom, validTo) values('GABONESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('GAMBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GEORGIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GERMAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GHANAIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GREEK', null, null);
insert into natENNationality (name, validFrom, validTo) values('GRENADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUATEMALAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUINEA-BISSAUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUYANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('HAITIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('HERZEGOVINIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('HONDURAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('HUNGARIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ICELANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('INDIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('INDONESIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('IRANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('IRAQI', null, null);
insert into natENNationality (name, validFrom, validTo) values('IRISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('ISRAELI', null, null);
insert into natENNationality (name, validFrom, validTo) values('ITALIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('IVORIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('JAMAICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('JAPANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('JORDANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('KAZAKHSTANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('KENYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('KITTIAN AND NEVISIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('KUWAITI', null, null);
insert into natENNationality (name, validFrom, validTo) values('KYRGYZ', null, null);
insert into natENNationality (name, validFrom, validTo) values('LAOTIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LATVIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LEBANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('LIBERIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LIBYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LIECHTENSTEINER', null, null);
insert into natENNationality (name, validFrom, validTo) values('LITHUANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LUXEMBOURGER', null, null);
insert into natENNationality (name, validFrom, validTo) values('MACEDONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALAGASY', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALAWIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALAYSIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALDIVAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALTESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('MARSHALLESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('MAURITANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MAURITIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MEXICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MICRONESIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOLDOVAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MONACAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MONGOLIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOROCCAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOSOTHO', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOTSWANA', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOZAMBICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NAMIBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NAURUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NEPALESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('NETHERLANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('NEW ZEALANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('NI-VANUATU', null, null);
insert into natENNationality (name, validFrom, validTo) values('NICARAGUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NIGERIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NIGERIEN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NORTH KOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NORTHERN IRISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('NORWEGIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('OMANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('PAKISTANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('PALAUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PANAMANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PAPUA NEW GUINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PARAGUAYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PERUVIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('POLISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('PORTUGUESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('QATARI', null, null);
insert into natENNationality (name, validFrom, validTo) values('ROMANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('RUSSIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('RWANDAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAINT LUCIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SALVADORAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAMOAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAN MARINESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAO TOMEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAUDI', null, null);
insert into natENNationality (name, validFrom, validTo) values('SCOTTISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('SENEGALESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('SERBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SEYCHELLOIS', null, null);
insert into natENNationality (name, validFrom, validTo) values('SIERRA LEONEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SINGAPOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SLOVAKIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SLOVENIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOLOMON ISLANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOMALI', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOUTH AFRICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOUTH KOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SPANISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('SRI LANKAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SUDANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('SURINAMER', null, null);
insert into natENNationality (name, validFrom, validTo) values('SWAZI', null, null);
insert into natENNationality (name, validFrom, validTo) values('SWEDISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('SWISS', null, null);
insert into natENNationality (name, validFrom, validTo) values('SYRIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TAIWANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('TAJIK', null, null);
insert into natENNationality (name, validFrom, validTo) values('TANZANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('THAI', null, null);
insert into natENNationality (name, validFrom, validTo) values('TOGOLESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('TONGAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TRINIDADIAN OR TOBAGONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TUNISIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TURKISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('TUVALUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('UGANDAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('UKRAINIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('URUGUAYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('UZBEKISTANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('VENEZUELAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('VIETNAMESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('WELSH', null, null);
insert into natENNationality (name, validFrom, validTo) values('YEMENITE', null, null);
insert into natENNationality (name, validFrom, validTo) values('ZAMBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ZIMBABWEAN', null, null);
